[package]
name = "mycgi"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"
log = "0.4.22"
rouille = "3.6.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.14"
url = "2.5.2"
